### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by gbtami** [amasend/lichees_python_SDK#37]
May I suggest to create and upload a release to pypi please?

**Comment by amasend** [comment]
Pypi upload is already done: https://pypi.org/project/async-lichess-sdk/
If you want me to create a release on github, yes it could be done.

**Comment by amasend** [comment]
Done.

**Comment by gbtami** [comment]
Ahh, my bad. Different name of GitHub repo and pypi package caused the problem for me.
Maybe explicit mention/link/badge to pypi package in README.md can be helpful.
