### ISSUE TITLE
number_of_rated_games is not set correctly.

### ISSUE THREAD

**Issue by m-bilgic** [amasend/lichees_python_SDK#41]
The code checks `if password is not None`. It should check `if number_of_rated_games is not None`

https://github.com/amasend/lichess_python_SDK/blob/ca9a10ce907b2dadb7e06a0136e669b1afb32cd9/lichess_client/endpoints/tournaments.py#L175

**Comment by amasend** [comment]
Bug confirmed.
Fix delivered in https://github.com/amasend/lichess_python_SDK/commit/ea33454d37fc1a366a53631914a0f578b340df14
Pypi version number: `1.1.0.7`
